# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'category_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.save_buttonbox = QtWidgets.QDialogButtonBox(Dialog)
        self.save_buttonbox.setGeometry(QtCore.QRect(10, 272, 381, 20))
        self.save_buttonbox.setOrientation(QtCore.Qt.Horizontal)
        self.save_buttonbox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.RestoreDefaults|QtWidgets.QDialogButtonBox.Save)
        self.save_buttonbox.setObjectName("save_buttonbox")
        self.category_title = QtWidgets.QLabel(Dialog)
        self.category_title.setGeometry(QtCore.QRect(20, 10, 201, 16))
        self.category_title.setAlignment(QtCore.Qt.AlignCenter)
        self.category_title.setObjectName("category_title")
        self.category_title2 = QtWidgets.QLabel(Dialog)
        self.category_title2.setGeometry(QtCore.QRect(240, 10, 141, 20))
        self.category_title2.setAlignment(QtCore.Qt.AlignCenter)
        self.category_title2.setObjectName("category_title2")
        self.category_listwidget = QtWidgets.QListWidget(Dialog)
        self.category_listwidget.setGeometry(QtCore.QRect(20, 40, 201, 171))
        self.category_listwidget.setObjectName("category_listwidget")
        self.family_listwidget = QtWidgets.QListWidget(Dialog)
        self.family_listwidget.setGeometry(QtCore.QRect(230, 40, 151, 171))
        self.family_listwidget.setObjectName("family_listwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(230, 240, 151, 24))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.family_name_linedit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.family_name_linedit.setMaximumSize(QtCore.QSize(16777215, 20))
        self.family_name_linedit.setObjectName("family_name_linedit")
        self.horizontalLayout.addWidget(self.family_name_linedit)
        self.add_family_pushbutton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.add_family_pushbutton.setMaximumSize(QtCore.QSize(30, 22))
        self.add_family_pushbutton.setObjectName("add_family_pushbutton")
        self.horizontalLayout.addWidget(self.add_family_pushbutton)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 240, 201, 24))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.category_name_lineedit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.category_name_lineedit.setMaximumSize(QtCore.QSize(16777215, 20))
        self.category_name_lineedit.setObjectName("category_name_lineedit")
        self.horizontalLayout_2.addWidget(self.category_name_lineedit)
        self.add_category_pushbutton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.add_category_pushbutton.setMaximumSize(QtCore.QSize(30, 22))
        self.add_category_pushbutton.setObjectName("add_category_pushbutton")
        self.horizontalLayout_2.addWidget(self.add_category_pushbutton)
        self.delete_category_button = QtWidgets.QPushButton(Dialog)
        self.delete_category_button.setGeometry(QtCore.QRect(20, 215, 201, 21))
        self.delete_category_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.delete_category_button.setObjectName("delete_category_button")
        self.delete_family_button = QtWidgets.QPushButton(Dialog)
        self.delete_family_button.setGeometry(QtCore.QRect(230, 215, 151, 21))
        self.delete_family_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.delete_family_button.setObjectName("delete_family_button")

        self.retranslateUi(Dialog)
        self.save_buttonbox.accepted.connect(Dialog.accept) # type: ignore
        self.save_buttonbox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.category_title.setText(_translate("Dialog", "Family Categories"))
        self.category_title2.setText(_translate("Dialog", "Category families"))
        self.family_name_linedit.setPlaceholderText(_translate("Dialog", "Family"))
        self.add_family_pushbutton.setText(_translate("Dialog", "Add"))
        self.category_name_lineedit.setPlaceholderText(_translate("Dialog", "Category name"))
        self.add_category_pushbutton.setText(_translate("Dialog", "Add"))
        self.delete_category_button.setText(_translate("Dialog", "Delete Selected Category"))
        self.delete_family_button.setText(_translate("Dialog", "Delete Selected Family"))
